#include <iostream>
#include <string>
#include <vector>
#include "common.h"

// Output which must be generated by the program.
static int required_output[] = {2,4,1,1,7,5,0,3,4,7,1,6,5,5,3,0};

number custom(number input, int out_count, int *out_required)
{
    number a, b, c;
    number out, oi;
    const int big_number = 1000000000;
    unsigned int epoch = big_number;
    bool pass = false;
    while (!pass) {
        a = input;
        b = 0, c = 0, out = 0, oi = 0;
        for (oi = 0 ; (a != 0) && (oi < out_count); oi++) {
            b = (a & 7) ^ 1;
            c = (a >> b);
            a = (a >> 3);
            b = (b ^ c) ^ 6;
            out = (b & 7);
            if (out != out_required[oi]) {
                break;
            }
        }
        pass = (oi >= out_count);
        if (pass) {
            return input;
        }
        if (--epoch == 0) {
            std::cout << "Reached " << input << std::endl;
            epoch = big_number;
        }
        input++;
    }
    return 0;
}

int main()
{
    std::cout << "Advent of Code 2024\nDay 17 - Chronospatial Computer\n";
    std::cout << "Part 2.\n";
    const char* file_name = "input17.txt";

    number a = 143380488355327L;
    number pass = custom(a, sizeof(required_output), required_output);

    std::cout << "Program succeeded, with value = " << pass << std::endl;

    return 0;
}
